<?php

namespace App\Models\Workflows;

use App\Enums\Application\ApplicationType;
use App\Http\ModelFilters\Workflows\TaskApplicationFilter;
use App\Models\AbstractModel;
use App\Models\Collaborators\Collaborator;
use App\Models\Compilation\RequirementsCollection;
use EloquentFilter\Filterable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * @mixin IdeHelperTaskApplication
 */
class TaskApplication extends AbstractModel
{
    use Filterable;

    protected $table = 'librarian_task_applications';

    /**
     * @return BelongsTo
     */
    public function applicant(): BelongsTo
    {
        return $this->belongsTo(Collaborator::class, 'user_id');
    }

    /**
     * @return BelongsTo
     */
    public function task(): BelongsTo
    {
        return $this->belongsTo(Task::class);
    }

    /*
    |--------------------------------------------------------------------------
    | Model Scopes
    |--------------------------------------------------------------------------
    */

    public function scopeForRequirementsCollection(Builder $builder, RequirementsCollection $reqCollection): Builder
    {
        return $builder->whereRelation('task.document.expression.work', fn ($q) => $q->where('primary_location_id', $reqCollection->id));
    }

    /*
    |--------------------------------------------------------------------------
    | Model Methods
    |--------------------------------------------------------------------------
    */

    /**
     * Exclude the given permissions from the autogenerated CRUD permissions.
     *
     * @return array<string, array<int, string>>
     */
    public static function excludeFromCrud(): array
    {
        return [
            ApplicationType::collaborate()->value => ['view', 'delete'],
        ];
    }

    public function modelFilter(): string
    {
        return $this->provideFilter(TaskApplicationFilter::class);
    }
}
