<?php

namespace App\Models\System;

use App\Enums\Application\ApplicationType;
use App\Enums\System\ProcessingJobStatus;
use App\Enums\System\ProcessingJobType;
use App\Models\AbstractModel;
use App\Models\Arachno\Spider;
use App\Models\Corpus\CatalogueWork;
use App\Models\Corpus\CatalogueWorkExpression;
use App\Models\Corpus\Work;
use App\Models\Corpus\WorkExpression;
use App\Models\Traits\HasUuidKey;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * @mixin IdeHelperProcessingJob
 */
class ProcessingJob extends AbstractModel
{
    use HasUuidKey;

    /** @var string */
    protected $table = 'corpus_processing_jobs';

    /** @var array<string, string> */
    protected $casts = [
        'payload' => 'array',
        'available_at' => 'datetime',
    ];

    /*
    |--------------------------------------------------------------------------
    | BOOT METHOD
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | Model Accessors
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | Model Mutators
    |--------------------------------------------------------------------------

    /*
    |--------------------------------------------------------------------------
    | Model Relations
    |--------------------------------------------------------------------------
    */

    /**
     * @return BelongsTo
     */
    public function spider(): BelongsTo
    {
        return $this->belongsTo(Spider::class);
    }

    /**
     * @return BelongsTo
     */
    public function catalogueWork(): BelongsTo
    {
        return $this->belongsTo(CatalogueWork::class, 'catalogue_work_id');
    }

    /**
     * @return BelongsTo
     */
    public function catalogueWorkExpression(): BelongsTo
    {
        return $this->belongsTo(CatalogueWorkExpression::class, 'catalogue_work_expression_id');
    }

    /**
     * @return BelongsTo
     */
    public function work(): BelongsTo
    {
        return $this->belongsTo(Work::class, 'work_id');
    }

    /**
     * @return BelongsTo
     */
    public function workExpression(): BelongsTo
    {
        return $this->belongsTo(WorkExpression::class, 'work_expression_id');
    }
    /*
    |--------------------------------------------------------------------------
    | Model Scopes
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | Model Methods
    |--------------------------------------------------------------------------
    */

    /**
     * Exclude the given permissions from the autogenerated CRUD permissions.
     *
     * @return array<string, array<int, string>>
     */
    public static function excludeFromCrud(): array
    {
        $fields = ['create', 'update', 'delete'];

        return [
            ApplicationType::admin()->value => $fields,
            ApplicationType::collaborate()->value => ['update', 'delete'],
            ApplicationType::my()->value => $fields,
        ];
    }

    /**
     * Create or update job for work.
     *
     * @param Work              $work
     * @param ProcessingJobType $type
     * @param array<mixed>      $payload
     *
     * @return mixed
     */
    public static function createForWork(Work $work, ProcessingJobType $type, array $payload = [])
    {
        return ProcessingJob::updateOrCreate([
            'job_type' => $type->value,
            'work_id' => $work->id,
        ], [
            'job_type' => $type->value,
            'work_id' => $work->id,
            'status' => ProcessingJobStatus::pending()->value,
            'payload' => !empty($payload) ? $payload : null,
            'available_at' => Carbon::now(),
        ]);
    }

    /**
     * Create or update a processing job available for a certain amount of minutes from now for the given type for a work.
     *
     * @param WorkExpression    $expression
     * @param ProcessingJobType $type
     * @param array<mixed>      $payload
     *
     * @return ProcessingJob
     */
    public static function createForWorkExpression(WorkExpression $expression, ProcessingJobType $type, array $payload = []): ProcessingJob
    {
        /** @var ProcessingJob */
        return ProcessingJob::create([
            'job_type' => $type->value,
            'work_expression_id' => $expression->id,
            'status' => ProcessingJobStatus::pending()->value,
            'payload' => !empty($payload) ? $payload : null,
        ]);
    }

    /**
     * Check if the processing job is complete.
     *
     * @return bool
     */
    public function isComplete(): bool
    {
        return ProcessingJobStatus::complete()->is($this->status);
    }
}
