export default {
  'act': 'Act',
  'agreement': 'Agreement',
  'amendment': 'Amendment',
  'announcement': 'Announcement',
  'bill': 'Bill',
  'bylaw': 'Bylaw',
  'change_notification': 'Change Notification',
  'circular': 'Circular',
  'code_of_ordinances': 'Code Of Ordinances',
  'code_of_practice': 'Code Of Practice',
  'code': 'Code',
  'constitution': 'Constitution',
  'convention': 'Convention',
  'decision': 'Decision',
  'declaration': 'Declaration',
  'decree': 'Decree',
  'direction': 'Direction',
  'directive': 'Directive',
  'gazette': 'Gazette',
  'guidance_notes': 'Guidance Notes',
  'guidance': 'Guidance',
  'guidelines': 'Guidelines',
  'law': 'Law',
  'legal_update': 'Legal Update',
  'legislation': 'Legislation',
  'legislative_instrument': 'Legislative Instrument',
  'measures': 'Measures',
  'ministerial_order': 'Ministerial Order',
  'notice': 'Notice',
  'notification': 'Notification',
  'order': 'Order',
  'ordinance': 'Ordinance',
  'permit': 'Permit',
  'policy': 'Policy',
  'procedures': 'Procedures',
  'proclamation': 'Proclamation',
  'proposal': 'Proposal',
  'regulation': 'Regulation',
  'resolution': 'Resolution',
  'rule': 'Rule',
  'standard': 'Standard',
  'statutory_instrument': 'Statutory Instrument',
  'treaty': 'Treaty',
};
