<?php

namespace Tests\Feature\Corpus\Collaborate;

use App\Models\Corpus\Doc;
use App\Models\Corpus\Work;
use App\Models\Corpus\WorkExpression;
use HotwiredLaravel\TurboLaravel\Testing\AssertableTurboStream;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Http\UploadedFile;
use Tests\Feature\Abstracts\CrudTestCase;

class WorkExpressionControllerTest extends CrudTestCase
{
    /** @var bool */
    protected bool $searchable = true;

    /** @var string */
    protected string $sortBy = 'start_date';

    protected static $work = 9999;

    protected bool $collaborate = true;

    /**
     * Get the class to be used for the CRUD operations.
     *
     * @return string
     */
    protected static function resource(): string
    {
        return WorkExpression::class;
    }

    /**
     * Get base resource route which will be added the suffix actions.
     *
     * @return string
     */
    protected static function resourceRoute(): string
    {
        return 'collaborate.work-expressions';
    }

    /**
     * Perform tasks before creation of the test model.
     *
     * @param Factory $factory
     * @param string  $route
     *
     * @return Factory
     */
    protected static function preCreate(Factory $factory, string $route): Factory
    {
        if (!Work::whereKey(static::$work)->exists()) {
            Work::factory()->create(['id' => static::$work]);
        }

        return $factory->state(['work_id' => static::$work]);
    }

    /**
     * Get payload for the base resource route.
     *
     * @param array $params
     *
     * @return array
     */
    protected static function resourceRouteParams(array $params): array
    {
        if (empty($params)) {
            return ['work' => static::$work];
        }

        if (isset($params['work_id'])) {
            return ['work' => $params['work_id']];
        }

        return parent::resourceRouteParams($params); // TODO: Change the autogenerated stub
    }

    /**
     * The list of database columns that should be visible on the pages.
     *
     * @return string[]
     */
    protected static function visibleFields(): array
    {
        return [];
    }

    /**
     * The list of database columns that should be visible on the pages with forms.
     *
     * @return string[]
     */
    protected static function visibleLabels(): array
    {
        return [];
    }

    /**
     * Get the labels that are visible on the show page.
     *
     * @return array<int, string>
     */
    protected static function visibleShowLabels(): array
    {
        return [];
    }

    /**
     * A list of actions to exclude from testing.
     * Options: index, create, store, edit, update, destroy.
     *
     * @return array
     */
    protected static function excludeActions(): array
    {
        return [
            'destroy',
        ];
    }

    /**
     * @return void
     */
    public function testItReturnsAStream(): void
    {
        $work = Work::factory()->create();
        $expressions = WorkExpression::factory()->count(2)->create([
            'work_id' => $work->id,
            'start_date' => $this->faker->date(),
        ]);

        $frame = "expressions_corpus_work_{$work->id}";

        $this->signIn($this->collaborateSuperUser());

        $this->post(route('collaborate.work-expressions.store', $work->id), [
            'start_date' => '2022-01-01',
            'file' => UploadedFile::fake()->image('test.png'),
        ])->assertSessionHasNoErrors()->assertRedirect();

        $this->get(route('collaborate.work-expressions.index', $work->id), ['turbo-frame' => $frame])
            ->assertSuccessful()
            ->assertTurboStream(function (AssertableTurboStream $streams) {
                return $streams->has(2);
            });

        $this->get(route('collaborate.work-expressions.json', $work->id))
            ->assertSuccessful();

        $doc = Doc::factory()->create();
        $expressions[0]->update(['doc_id' => $doc->id]);

        $this->put(route('collaborate.work-expressions.update', ['work' => $work->id, 'work_expression' => $expressions[0]->id]), [
            'start_date' => '2022-01-01',
            'file' => UploadedFile::fake()->image('test.pdf'),
        ])->assertSessionHasNoErrors()->assertRedirect();
    }

    public function testActivatingExpressions(): void
    {
        $work = Work::factory()->create();
        $active = WorkExpression::factory()->create(['work_id' => $work->id]);
        $toActivate = WorkExpression::factory()->create(['work_id' => $work->id]);
        $work->update(['active_work_expression_id' => $active->id]);
        $this->signIn($this->collaborateSuperUser());

        $this->assertDatabaseHas(Work::class, ['active_work_expression_id' => $active->id, 'id' => $work->id]);
        $this->assertDatabaseMissing(Work::class, ['active_work_expression_id' => $toActivate->id, 'id' => $work->id]);

        $this->put(route('collaborate.work-expressions.activate', ['expression' => $toActivate]));

        $this->assertDatabaseMissing(Work::class, ['active_work_expression_id' => $active->id, 'id' => $work->id]);

        $this->assertDatabaseHas(Work::class, ['active_work_expression_id' => $toActivate->id, 'id' => $work->id]);
    }
}
