<?php

namespace App\Support;

class Languages
{
    /** @var array<string, string> */
    public static array $alpha3To2 = [
        'aar' => 'aa', 'abk' => 'ab', 'afr' => 'af', 'aka' => 'ak', 'amh' => 'am', 'ara' => 'ar', 'arg' => 'an', 'asm' => 'as', 'ava' => 'av', 'ave' => 'ae', 'aym' => 'ay', 'aze' => 'az', 'bak' => 'ba', 'bam' => 'bm', 'bel' => 'be', 'ben' => 'bn', 'bih' => 'bh', 'bis' => 'bi', 'bod' => 'bo', 'bos' => 'bs', 'bre' => 'br', 'bul' => 'bg', 'cat' => 'ca', 'ces' => 'cs', 'cha' => 'ch', 'che' => 'ce', 'chu' => 'cu', 'chv' => 'cv', 'cor' => 'kw', 'cos' => 'co', 'cre' => 'cr', 'cym' => 'cy', 'dan' => 'da', 'deu' => 'de', 'div' => 'dv', 'dzo' => 'dz', 'ell' => 'el', 'eng' => 'en', 'epo' => 'eo', 'est' => 'et', 'eus' => 'eu', 'ewe' => 'ee', 'fao' => 'fo', 'fas' => 'fa', 'fij' => 'fj', 'fin' => 'fi', 'fra' => 'fr', 'fry' => 'fy', 'ful' => 'ff', 'gla' => 'gd', 'gle' => 'ga', 'glg' => 'gl', 'glv' => 'gv', 'grn' => 'gn', 'guj' => 'gu', 'hat' => 'ht', 'hau' => 'ha', 'heb' => 'he', 'her' => 'hz', 'hin' => 'hi', 'hmo' => 'ho', 'hrv' => 'hr', 'hun' => 'hu', 'hye' => 'hy', 'ibo' => 'ig', 'ido' => 'io', 'iii' => 'ii', 'iku' => 'iu', 'ile' => 'ie', 'ina' => 'ia', 'ind' => 'id', 'ipk' => 'ik', 'isl' => 'is', 'ita' => 'it', 'jav' => 'jv', 'jpn' => 'ja', 'kal' => 'kl', 'kan' => 'kn', 'kas' => 'ks', 'kat' => 'ka', 'kau' => 'kr', 'kaz' => 'kk', 'khm' => 'km', 'kik' => 'ki', 'kin' => 'rw', 'kir' => 'ky', 'kom' => 'kv', 'kon' => 'kg', 'kor' => 'ko', 'kua' => 'kj', 'kur' => 'ku', 'lao' => 'lo', 'lat' => 'la', 'lav' => 'lv', 'lim' => 'li', 'lin' => 'ln', 'lit' => 'lt', 'ltz' => 'lb', 'lub' => 'lu', 'lug' => 'lg', 'mah' => 'mh', 'mal' => 'ml', 'mar' => 'mr', 'mkd' => 'mk', 'mlg' => 'mg', 'mlt' => 'mt', 'mon' => 'mn', 'mri' => 'mi', 'msa' => 'ms', 'mya' => 'my', 'nau' => 'na', 'nav' => 'nv', 'nbl' => 'nr', 'nde' => 'nd', 'ndo' => 'ng', 'nep' => 'ne', 'nld' => 'nl', 'nno' => 'nn', 'nob' => 'nb', 'nor' => 'no', 'nya' => 'ny', 'oci' => 'oc', 'oji' => 'oj', 'ori' => 'or', 'orm' => 'om', 'oss' => 'os', 'pan' => 'pa', 'pli' => 'pi', 'pol' => 'pl', 'por' => 'pt', 'pus' => 'ps', 'que' => 'qu', 'roh' => 'rm', 'ron' => 'ro', 'run' => 'rn', 'rus' => 'ru', 'sag' => 'sg', 'san' => 'sa', 'sin' => 'si', 'slk' => 'sk', 'slv' => 'sl', 'sme' => 'se', 'smo' => 'sm', 'sna' => 'sn', 'snd' => 'sd', 'som' => 'so', 'sot' => 'st', 'spa' => 'es', 'sqi' => 'sq', 'srd' => 'sc', 'srp' => 'sr', 'ssw' => 'ss', 'sun' => 'su', 'swa' => 'sw', 'swe' => 'sv', 'tah' => 'ty', 'tam' => 'ta', 'tat' => 'tt', 'tel' => 'te', 'tgk' => 'tg', 'tgl' => 'tl', 'tha' => 'th', 'tir' => 'ti', 'ton' => 'to', 'tsn' => 'tn', 'tso' => 'ts', 'tuk' => 'tk', 'tur' => 'tr', 'twi' => 'tw', 'uig' => 'ug', 'ukr' => 'uk', 'urd' => 'ur', 'uzb' => 'uz', 'ven' => 've', 'vie' => 'vi', 'vol' => 'vo', 'wln' => 'wa', 'wol' => 'wo', 'xho' => 'xh', 'yid' => 'yi', 'yor' => 'yo', 'zha' => 'za', 'zho' => 'zh', 'zul' => 'zu',
    ];

    private const LANGUAGES = [
        'abk' => [
            'name' => 'Abkhaz',
            'native' => 'аҧсуа бызшәа, аҧсшәа',
            'iso639-1' => 'ab',
            'iso639-2/t' => 'abk',
            'iso639-2/b' => 'abk',
            'iso639-3' => 'abk',
        ],
        'aar' => [
            'name' => 'Afar',
            'native' => 'Afaraf',
            'iso639-1' => 'aa',
            'iso639-2/t' => 'aar',
            'iso639-2/b' => 'aar',
            'iso639-3' => 'aar',
        ],
        'afr' => [
            'name' => 'Afrikaans',
            'native' => 'Afrikaans',
            'iso639-1' => 'af',
            'iso639-2/t' => 'afr',
            'iso639-2/b' => 'afr',
            'iso639-3' => 'afr',
        ],
        'aka' => [
            'name' => 'Akan',
            'native' => 'Akan',
            'iso639-1' => 'ak',
            'iso639-2/t' => 'aka',
            'iso639-2/b' => 'aka',
            'iso639-3' => 'aka + 2',
        ],
        'sqi' => [
            'name' => 'Albanian',
            'native' => 'Shqip',
            'iso639-1' => 'sq',
            'iso639-2/t' => 'sqi',
            'iso639-2/b' => 'alb',
            'iso639-3' => 'sqi + 4',
        ],
        'amh' => [
            'name' => 'Amharic',
            'native' => 'አማርኛ',
            'iso639-1' => 'am',
            'iso639-2/t' => 'amh',
            'iso639-2/b' => 'amh',
            'iso639-3' => 'amh',
        ],
        'ara' => [
            'name' => 'Arabic',
            'native' => 'العربية',
            'iso639-1' => 'ar',
            'iso639-2/t' => 'ara',
            'iso639-2/b' => 'ara',
            'iso639-3' => 'ara + 30',
        ],
        'arg' => [
            'name' => 'Aragonese',
            'native' => 'Aragonés',
            'iso639-1' => 'an',
            'iso639-2/t' => 'arg',
            'iso639-2/b' => 'arg',
            'iso639-3' => 'arg',
        ],
        'hye' => [
            'name' => 'Armenian',
            'native' => 'հայերեն',
            'iso639-1' => 'hy',
            'iso639-2/t' => 'hye',
            'iso639-2/b' => 'arm',
            'iso639-3' => 'hye',
        ],
        'asm' => [
            'name' => 'Assamese',
            'native' => 'অসমীয়া',
            'iso639-1' => 'as',
            'iso639-2/t' => 'asm',
            'iso639-2/b' => 'asm',
            'iso639-3' => 'asm',
        ],
        'ava' => [
            'name' => 'Avaric',
            'native' => 'авар мацӏ, магӏарул мацӏ',
            'iso639-1' => 'av',
            'iso639-2/t' => 'ava',
            'iso639-2/b' => 'ava',
            'iso639-3' => 'ava',
        ],
        'ave' => [
            'name' => 'Avestan',
            'native' => 'Avesta',
            'iso639-1' => 'ae',
            'iso639-2/t' => 'ave',
            'iso639-2/b' => 'ave',
            'iso639-3' => 'ave',
        ],
        'aym' => [
            'name' => 'Aymara',
            'native' => 'Aymar Aru',
            'iso639-1' => 'ay',
            'iso639-2/t' => 'aym',
            'iso639-2/b' => 'aym',
            'iso639-3' => 'aym + 2',
        ],
        'aze' => [
            'name' => 'Azerbaijani',
            'native' => 'Azərbaycan Dili',
            'iso639-1' => 'az',
            'iso639-2/t' => 'aze',
            'iso639-2/b' => 'aze',
            'iso639-3' => 'aze + 2',
        ],
        'bam' => [
            'name' => 'Bambara',
            'native' => 'Bamanankan',
            'iso639-1' => 'bm',
            'iso639-2/t' => 'bam',
            'iso639-2/b' => 'bam',
            'iso639-3' => 'bam',
        ],
        'bak' => [
            'name' => 'Bashkir',
            'native' => 'башҡорт теле',
            'iso639-1' => 'ba',
            'iso639-2/t' => 'bak',
            'iso639-2/b' => 'bak',
            'iso639-3' => 'bak',
        ],
        'eus' => [
            'name' => 'Basque',
            'native' => 'Euskara, Euskera',
            'iso639-1' => 'eu',
            'iso639-2/t' => 'eus',
            'iso639-2/b' => 'baq',
            'iso639-3' => 'eus',
        ],
        'bel' => [
            'name' => 'Belarusian',
            'native' => 'беларуская мова',
            'iso639-1' => 'be',
            'iso639-2/t' => 'bel',
            'iso639-2/b' => 'bel',
            'iso639-3' => 'bel',
        ],
        'ben' => [
            'name' => 'Bengali, Bangla',
            'native' => 'বাংলা',
            'iso639-1' => 'bn',
            'iso639-2/t' => 'ben',
            'iso639-2/b' => 'ben',
            'iso639-3' => 'ben',
        ],
        'bih' => [
            'name' => 'Bihari',
            'native' => 'भोजपुरी',
            'iso639-1' => 'bh',
            'iso639-2/t' => 'bih',
            'iso639-2/b' => 'bih',
            'iso639-3' => 'bih',
        ],
        'bis' => [
            'name' => 'Bislama',
            'native' => 'Bislama',
            'iso639-1' => 'bi',
            'iso639-2/t' => 'bis',
            'iso639-2/b' => 'bis',
            'iso639-3' => 'bis',
        ],
        'bos' => [
            'name' => 'Bosnian',
            'native' => 'Bosanski Jezik',
            'iso639-1' => 'bs',
            'iso639-2/t' => 'bos',
            'iso639-2/b' => 'bos',
            'iso639-3' => 'bos',
        ],
        'bre' => [
            'name' => 'Breton',
            'native' => 'Brezhoneg',
            'iso639-1' => 'br',
            'iso639-2/t' => 'bre',
            'iso639-2/b' => 'bre',
            'iso639-3' => 'bre',
        ],
        'bul' => [
            'name' => 'Bulgarian',
            'native' => 'български език',
            'iso639-1' => 'bg',
            'iso639-2/t' => 'bul',
            'iso639-2/b' => 'bul',
            'iso639-3' => 'bul',
        ],
        'mya' => [
            'name' => 'Burmese',
            'native' => 'ဗမာစာ',
            'iso639-1' => 'my',
            'iso639-2/t' => 'mya',
            'iso639-2/b' => 'bur',
            'iso639-3' => 'mya',
        ],
        'cat' => [
            'name' => 'Catalan, Valencian',
            'native' => 'Català, Valencià',
            'iso639-1' => 'ca',
            'iso639-2/t' => 'cat',
            'iso639-2/b' => 'cat',
            'iso639-3' => 'cat',
        ],
        'cha' => [
            'name' => 'Chamorro',
            'native' => 'Chamoru',
            'iso639-1' => 'ch',
            'iso639-2/t' => 'cha',
            'iso639-2/b' => 'cha',
            'iso639-3' => 'cha',
        ],
        'che' => [
            'name' => 'Chechen',
            'native' => 'нохчийн мотт',
            'iso639-1' => 'ce',
            'iso639-2/t' => 'che',
            'iso639-2/b' => 'che',
            'iso639-3' => 'che',
        ],
        'nya' => [
            'name' => 'Chichewa, Chewa, Nyanja',
            'native' => 'Chicheŵa, Chinyanja',
            'iso639-1' => 'ny',
            'iso639-2/t' => 'nya',
            'iso639-2/b' => 'nya',
            'iso639-3' => 'nya',
        ],
        'zho' => [
            'name' => 'Chinese',
            'native' => '中文 (zhōngwén), 汉语, 漢語',
            'iso639-1' => 'zh',
            'iso639-2/t' => 'zho',
            'iso639-2/b' => 'chi',
            'iso639-3' => 'zho + 13',
        ],
        'chv' => [
            'name' => 'Chuvash',
            'native' => 'чӑваш чӗлхи',
            'iso639-1' => 'cv',
            'iso639-2/t' => 'chv',
            'iso639-2/b' => 'chv',
            'iso639-3' => 'chv',
        ],
        'cor' => [
            'name' => 'Cornish',
            'native' => 'Kernewek',
            'iso639-1' => 'kw',
            'iso639-2/t' => 'cor',
            'iso639-2/b' => 'cor',
            'iso639-3' => 'cor',
        ],
        'cos' => [
            'name' => 'Corsican',
            'native' => 'Corsu, Lingua Corsa',
            'iso639-1' => 'co',
            'iso639-2/t' => 'cos',
            'iso639-2/b' => 'cos',
            'iso639-3' => 'cos',
        ],
        'cre' => [
            'name' => 'Cree',
            'native' => 'ᓀᐦᐃᔭᐍᐏᐣ',
            'iso639-1' => 'cr',
            'iso639-2/t' => 'cre',
            'iso639-2/b' => 'cre',
            'iso639-3' => 'cre + 6',
        ],
        'hrv' => [
            'name' => 'Croatian',
            'native' => 'Hrvatski Jezik',
            'iso639-1' => 'hr',
            'iso639-2/t' => 'hrv',
            'iso639-2/b' => 'hrv',
            'iso639-3' => 'hrv',
        ],
        'ces' => [
            'name' => 'Czech',
            'native' => 'čeština, český Jazyk',
            'iso639-1' => 'cs',
            'iso639-2/t' => 'ces',
            'iso639-2/b' => 'cze',
            'iso639-3' => 'ces',
        ],
        'dan' => [
            'name' => 'Danish',
            'native' => 'Dansk',
            'iso639-1' => 'da',
            'iso639-2/t' => 'dan',
            'iso639-2/b' => 'dan',
            'iso639-3' => 'dan',
        ],
        'div' => [
            'name' => 'Divehi, Dhivehi, Maldivian',
            'native' => 'ދިވެހި',
            'iso639-1' => 'dv',
            'iso639-2/t' => 'div',
            'iso639-2/b' => 'div',
            'iso639-3' => 'div',
        ],
        'nld' => [
            'name' => 'Dutch',
            'native' => 'Nederlands, Vlaams',
            'iso639-1' => 'nl',
            'iso639-2/t' => 'nld',
            'iso639-2/b' => 'dut',
            'iso639-3' => 'nld',
        ],
        'dzo' => [
            'name' => 'Dzongkha',
            'native' => 'རྫོང་ཁ',
            'iso639-1' => 'dz',
            'iso639-2/t' => 'dzo',
            'iso639-2/b' => 'dzo',
            'iso639-3' => 'dzo',
        ],
        'eng' => [
            'name' => 'English',
            'native' => 'English',
            'iso639-1' => 'en',
            'iso639-2/t' => 'eng',
            'iso639-2/b' => 'eng',
            'iso639-3' => 'eng',
        ],
        'epo' => [
            'name' => 'Esperanto',
            'native' => 'Esperanto',
            'iso639-1' => 'eo',
            'iso639-2/t' => 'epo',
            'iso639-2/b' => 'epo',
            'iso639-3' => 'epo',
        ],
        'est' => [
            'name' => 'Estonian',
            'native' => 'Eesti, Eesti Keel',
            'iso639-1' => 'et',
            'iso639-2/t' => 'est',
            'iso639-2/b' => 'est',
            'iso639-3' => 'est + 2',
        ],
        'ewe' => [
            'name' => 'Ewe',
            'native' => 'Eʋegbe',
            'iso639-1' => 'ee',
            'iso639-2/t' => 'ewe',
            'iso639-2/b' => 'ewe',
            'iso639-3' => 'ewe',
        ],
        'fao' => [
            'name' => 'Faroese',
            'native' => 'Føroyskt',
            'iso639-1' => 'fo',
            'iso639-2/t' => 'fao',
            'iso639-2/b' => 'fao',
            'iso639-3' => 'fao',
        ],
        'fij' => [
            'name' => 'Fijian',
            'native' => 'Vosa Vakaviti',
            'iso639-1' => 'fj',
            'iso639-2/t' => 'fij',
            'iso639-2/b' => 'fij',
            'iso639-3' => 'fij',
        ],
        'fin' => [
            'name' => 'Finnish',
            'native' => 'Suomi, Suomen Kieli',
            'iso639-1' => 'fi',
            'iso639-2/t' => 'fin',
            'iso639-2/b' => 'fin',
            'iso639-3' => 'fin',
        ],
        'fra' => [
            'name' => 'French',
            'native' => 'Français, Langue Française',
            'iso639-1' => 'fr',
            'iso639-2/t' => 'fra',
            'iso639-2/b' => 'fre',
            'iso639-3' => 'fra',
        ],
        'ful' => [
            'name' => 'Fula, Fulah, Pulaar, Pular',
            'native' => 'Fulfulde, Pulaar, Pular',
            'iso639-1' => 'ff',
            'iso639-2/t' => 'ful',
            'iso639-2/b' => 'ful',
            'iso639-3' => 'ful + 9',
        ],
        'glg' => [
            'name' => 'Galician',
            'native' => 'Galego',
            'iso639-1' => 'gl',
            'iso639-2/t' => 'glg',
            'iso639-2/b' => 'glg',
            'iso639-3' => 'glg',
        ],
        'kat' => [
            'name' => 'Georgian',
            'native' => 'ქართული',
            'iso639-1' => 'ka',
            'iso639-2/t' => 'kat',
            'iso639-2/b' => 'geo',
            'iso639-3' => 'kat',
        ],
        'deu' => [
            'name' => 'German',
            'native' => 'Deutsch',
            'iso639-1' => 'de',
            'iso639-2/t' => 'deu',
            'iso639-2/b' => 'ger',
            'iso639-3' => 'deu',
        ],
        'ell' => [
            'name' => 'Greek (modern)',
            'native' => 'ελληνικά',
            'iso639-1' => 'el',
            'iso639-2/t' => 'ell',
            'iso639-2/b' => 'gre',
            'iso639-3' => 'ell',
        ],
        'grn' => [
            'name' => 'Guaraní',
            'native' => "Avañe'ẽ",
            'iso639-1' => 'gn',
            'iso639-2/t' => 'grn',
            'iso639-2/b' => 'grn',
            'iso639-3' => 'grn + 5',
        ],
        'guj' => [
            'name' => 'Gujarati',
            'native' => 'ગુજરાતી',
            'iso639-1' => 'gu',
            'iso639-2/t' => 'guj',
            'iso639-2/b' => 'guj',
            'iso639-3' => 'guj',
        ],
        'hat' => [
            'name' => 'Haitian, Haitian Creole',
            'native' => 'Kreyòl Ayisyen',
            'iso639-1' => 'ht',
            'iso639-2/t' => 'hat',
            'iso639-2/b' => 'hat',
            'iso639-3' => 'hat',
        ],
        'hau' => [
            'name' => 'Hausa',
            'native' => '(hausa) هَوُسَ',
            'iso639-1' => 'ha',
            'iso639-2/t' => 'hau',
            'iso639-2/b' => 'hau',
            'iso639-3' => 'hau',
        ],
        'heb' => [
            'name' => 'Hebrew (modern)',
            'native' => 'עברית',
            'iso639-1' => 'he',
            'iso639-2/t' => 'heb',
            'iso639-2/b' => 'heb',
            'iso639-3' => 'heb',
        ],
        'her' => [
            'name' => 'Herero',
            'native' => 'Otjiherero',
            'iso639-1' => 'hz',
            'iso639-2/t' => 'her',
            'iso639-2/b' => 'her',
            'iso639-3' => 'her',
        ],
        'hin' => [
            'name' => 'Hindi',
            'native' => 'हिन्दी, हिंदी',
            'iso639-1' => 'hi',
            'iso639-2/t' => 'hin',
            'iso639-2/b' => 'hin',
            'iso639-3' => 'hin',
        ],
        'hmo' => [
            'name' => 'Hiri Motu',
            'native' => 'Hiri Motu',
            'iso639-1' => 'ho',
            'iso639-2/t' => 'hmo',
            'iso639-2/b' => 'hmo',
            'iso639-3' => 'hmo',
        ],
        'hun' => [
            'name' => 'Hungarian',
            'native' => 'Magyar',
            'iso639-1' => 'hu',
            'iso639-2/t' => 'hun',
            'iso639-2/b' => 'hun',
            'iso639-3' => 'hun',
        ],
        'ina' => [
            'name' => 'Interlingua',
            'native' => 'Interlingua',
            'iso639-1' => 'ia',
            'iso639-2/t' => 'ina',
            'iso639-2/b' => 'ina',
            'iso639-3' => 'ina',
        ],
        'ind' => [
            'name' => 'Indonesian',
            'native' => 'Bahasa Indonesia',
            'iso639-1' => 'id',
            'iso639-2/t' => 'ind',
            'iso639-2/b' => 'ind',
            'iso639-3' => 'ind',
        ],
        'ile' => [
            'name' => 'Interlingue',
            'native' => 'Originally Called Occidental; Then Interlingue After WWII',
            'iso639-1' => 'ie',
            'iso639-2/t' => 'ile',
            'iso639-2/b' => 'ile',
            'iso639-3' => 'ile',
        ],
        'gle' => [
            'name' => 'Irish',
            'native' => 'Gaeilge',
            'iso639-1' => 'ga',
            'iso639-2/t' => 'gle',
            'iso639-2/b' => 'gle',
            'iso639-3' => 'gle',
        ],
        'ibo' => [
            'name' => 'Igbo',
            'native' => 'Asụsụ Igbo',
            'iso639-1' => 'ig',
            'iso639-2/t' => 'ibo',
            'iso639-2/b' => 'ibo',
            'iso639-3' => 'ibo',
        ],
        'ipk' => [
            'name' => 'Inupiaq',
            'native' => 'Iñupiaq, Iñupiatun',
            'iso639-1' => 'ik',
            'iso639-2/t' => 'ipk',
            'iso639-2/b' => 'ipk',
            'iso639-3' => 'ipk + 2',
        ],
        'ido' => [
            'name' => 'Ido',
            'native' => 'Ido',
            'iso639-1' => 'io',
            'iso639-2/t' => 'ido',
            'iso639-2/b' => 'ido',
            'iso639-3' => 'ido',
        ],
        'isl' => [
            'name' => 'Icelandic',
            'native' => 'íslenska',
            'iso639-1' => 'is',
            'iso639-2/t' => 'isl',
            'iso639-2/b' => 'ice',
            'iso639-3' => 'isl',
        ],
        'ita' => [
            'name' => 'Italian',
            'native' => 'Italiano',
            'iso639-1' => 'it',
            'iso639-2/t' => 'ita',
            'iso639-2/b' => 'ita',
            'iso639-3' => 'ita',
        ],
        'iku' => [
            'name' => 'Inuktitut',
            'native' => 'ᐃᓄᒃᑎᑐᑦ',
            'iso639-1' => 'iu',
            'iso639-2/t' => 'iku',
            'iso639-2/b' => 'iku',
            'iso639-3' => 'iku + 2',
        ],
        'jpn' => [
            'name' => 'Japanese',
            'native' => '日本語 (にほんご)',
            'iso639-1' => 'ja',
            'iso639-2/t' => 'jpn',
            'iso639-2/b' => 'jpn',
            'iso639-3' => 'jpn',
        ],
        'jav' => [
            'name' => 'Javanese',
            'native' => 'Basa Jawa',
            'iso639-1' => 'jv',
            'iso639-2/t' => 'jav',
            'iso639-2/b' => 'jav',
            'iso639-3' => 'jav',
        ],
        'kal' => [
            'name' => 'Kalaallisut, Greenlandic',
            'native' => 'Kalaallisut, Kalaallit Oqaasii',
            'iso639-1' => 'kl',
            'iso639-2/t' => 'kal',
            'iso639-2/b' => 'kal',
            'iso639-3' => 'kal',
        ],
        'kan' => [
            'name' => 'Kannada',
            'native' => 'ಕನ್ನಡ',
            'iso639-1' => 'kn',
            'iso639-2/t' => 'kan',
            'iso639-2/b' => 'kan',
            'iso639-3' => 'kan',
        ],
        'kau' => [
            'name' => 'Kanuri',
            'native' => 'Kanuri',
            'iso639-1' => 'kr',
            'iso639-2/t' => 'kau',
            'iso639-2/b' => 'kau',
            'iso639-3' => 'kau + 3',
        ],
        'kas' => [
            'name' => 'Kashmiri',
            'native' => 'कश्मीरी, كشميري‎',
            'iso639-1' => 'ks',
            'iso639-2/t' => 'kas',
            'iso639-2/b' => 'kas',
            'iso639-3' => 'kas',
        ],
        'kaz' => [
            'name' => 'Kazakh',
            'native' => 'қазақ тілі',
            'iso639-1' => 'kk',
            'iso639-2/t' => 'kaz',
            'iso639-2/b' => 'kaz',
            'iso639-3' => 'kaz',
        ],
        'khm' => [
            'name' => 'Khmer',
            'native' => 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ',
            'iso639-1' => 'km',
            'iso639-2/t' => 'khm',
            'iso639-2/b' => 'khm',
            'iso639-3' => 'khm',
        ],
        'kik' => [
            'name' => 'Kikuyu, Gikuyu',
            'native' => 'Gĩkũyũ',
            'iso639-1' => 'ki',
            'iso639-2/t' => 'kik',
            'iso639-2/b' => 'kik',
            'iso639-3' => 'kik',
        ],
        'kin' => [
            'name' => 'Kinyarwanda',
            'native' => 'Ikinyarwanda',
            'iso639-1' => 'rw',
            'iso639-2/t' => 'kin',
            'iso639-2/b' => 'kin',
            'iso639-3' => 'kin',
        ],
        'kir' => [
            'name' => 'Kyrgyz',
            'native' => 'кыргызча, кыргыз тили',
            'iso639-1' => 'ky',
            'iso639-2/t' => 'kir',
            'iso639-2/b' => 'kir',
            'iso639-3' => 'kir',
        ],
        'kom' => [
            'name' => 'Komi',
            'native' => 'коми кыв',
            'iso639-1' => 'kv',
            'iso639-2/t' => 'kom',
            'iso639-2/b' => 'kom',
            'iso639-3' => 'kom + 2',
        ],
        'kon' => [
            'name' => 'Kongo',
            'native' => 'Kikongo',
            'iso639-1' => 'kg',
            'iso639-2/t' => 'kon',
            'iso639-2/b' => 'kon',
            'iso639-3' => 'kon + 3',
        ],
        'kor' => [
            'name' => 'Korean',
            'native' => '한국어, 조선어',
            'iso639-1' => 'ko',
            'iso639-2/t' => 'kor',
            'iso639-2/b' => 'kor',
            'iso639-3' => 'kor',
        ],
        'kur' => [
            'name' => 'Kurdish',
            'native' => 'Kurdî, كوردی‎',
            'iso639-1' => 'ku',
            'iso639-2/t' => 'kur',
            'iso639-2/b' => 'kur',
            'iso639-3' => 'kur + 3',
        ],
        'kua' => [
            'name' => 'Kwanyama, Kuanyama',
            'native' => 'Kuanyama',
            'iso639-1' => 'kj',
            'iso639-2/t' => 'kua',
            'iso639-2/b' => 'kua',
            'iso639-3' => 'kua',
        ],
        'lat' => [
            'name' => 'Latin',
            'native' => 'Latine, Lingua Latina',
            'iso639-1' => 'la',
            'iso639-2/t' => 'lat',
            'iso639-2/b' => 'lat',
            'iso639-3' => 'lat',
        ],
        'ltz' => [
            'name' => 'Luxembourgish, Letzeburgesch',
            'native' => 'Lëtzebuergesch',
            'iso639-1' => 'lb',
            'iso639-2/t' => 'ltz',
            'iso639-2/b' => 'ltz',
            'iso639-3' => 'ltz',
        ],
        'lug' => [
            'name' => 'Ganda',
            'native' => 'Luganda',
            'iso639-1' => 'lg',
            'iso639-2/t' => 'lug',
            'iso639-2/b' => 'lug',
            'iso639-3' => 'lug',
        ],
        'lim' => [
            'name' => 'Limburgish, Limburgan, Limburger',
            'native' => 'Limburgs',
            'iso639-1' => 'li',
            'iso639-2/t' => 'lim',
            'iso639-2/b' => 'lim',
            'iso639-3' => 'lim',
        ],
        'lin' => [
            'name' => 'Lingala',
            'native' => 'Lingála',
            'iso639-1' => 'ln',
            'iso639-2/t' => 'lin',
            'iso639-2/b' => 'lin',
            'iso639-3' => 'lin',
        ],
        'lao' => [
            'name' => 'Lao',
            'native' => 'ພາສາລາວ',
            'iso639-1' => 'lo',
            'iso639-2/t' => 'lao',
            'iso639-2/b' => 'lao',
            'iso639-3' => 'lao',
        ],
        'lit' => [
            'name' => 'Lithuanian',
            'native' => 'Lietuvių Kalba',
            'iso639-1' => 'lt',
            'iso639-2/t' => 'lit',
            'iso639-2/b' => 'lit',
            'iso639-3' => 'lit',
        ],
        'lub' => [
            'name' => 'Luba-katanga',
            'native' => 'Tshiluba',
            'iso639-1' => 'lu',
            'iso639-2/t' => 'lub',
            'iso639-2/b' => 'lub',
            'iso639-3' => 'lub',
        ],
        'lav' => [
            'name' => 'Latvian',
            'native' => 'Latviešu Valoda',
            'iso639-1' => 'lv',
            'iso639-2/t' => 'lav',
            'iso639-2/b' => 'lav',
            'iso639-3' => 'lav + 2',
        ],
        'glv' => [
            'name' => 'Manx',
            'native' => 'Gaelg, Gailck',
            'iso639-1' => 'gv',
            'iso639-2/t' => 'glv',
            'iso639-2/b' => 'glv',
            'iso639-3' => 'glv',
        ],
        'mkd' => [
            'name' => 'Macedonian',
            'native' => 'македонски јазик',
            'iso639-1' => 'mk',
            'iso639-2/t' => 'mkd',
            'iso639-2/b' => 'mac',
            'iso639-3' => 'mkd',
        ],
        'mlg' => [
            'name' => 'Malagasy',
            'native' => 'Fiteny Malagasy',
            'iso639-1' => 'mg',
            'iso639-2/t' => 'mlg',
            'iso639-2/b' => 'mlg',
            'iso639-3' => 'mlg + 10',
        ],
        'msa' => [
            'name' => 'Malay',
            'native' => 'Bahasa Melayu, بهاس ملايو‎',
            'iso639-1' => 'ms',
            'iso639-2/t' => 'msa',
            'iso639-2/b' => 'may',
            'iso639-3' => 'msa + 13',
        ],
        'mal' => [
            'name' => 'Malayalam',
            'native' => 'മലയാളം',
            'iso639-1' => 'ml',
            'iso639-2/t' => 'mal',
            'iso639-2/b' => 'mal',
            'iso639-3' => 'mal',
        ],
        'mlt' => [
            'name' => 'Maltese',
            'native' => 'Malti',
            'iso639-1' => 'mt',
            'iso639-2/t' => 'mlt',
            'iso639-2/b' => 'mlt',
            'iso639-3' => 'mlt',
        ],
        'mri' => [
            'name' => 'Māori',
            'native' => 'Te Reo Māori',
            'iso639-1' => 'mi',
            'iso639-2/t' => 'mri',
            'iso639-2/b' => 'mao',
            'iso639-3' => 'mri',
        ],
        'mar' => [
            'name' => 'Marathi (marāṭhī)',
            'native' => 'मराठी',
            'iso639-1' => 'mr',
            'iso639-2/t' => 'mar',
            'iso639-2/b' => 'mar',
            'iso639-3' => 'mar',
        ],
        'mah' => [
            'name' => 'Marshallese',
            'native' => 'Kajin M̧ajeļ',
            'iso639-1' => 'mh',
            'iso639-2/t' => 'mah',
            'iso639-2/b' => 'mah',
            'iso639-3' => 'mah',
        ],
        'mon' => [
            'name' => 'Mongolian',
            'native' => 'монгол',
            'iso639-1' => 'mn',
            'iso639-2/t' => 'mon',
            'iso639-2/b' => 'mon',
            'iso639-3' => 'mon + 2',
        ],
        'nau' => [
            'name' => 'Nauru',
            'native' => 'Ekakairũ Naoero',
            'iso639-1' => 'na',
            'iso639-2/t' => 'nau',
            'iso639-2/b' => 'nau',
            'iso639-3' => 'nau',
        ],
        'nav' => [
            'name' => 'Navajo, Navaho',
            'native' => 'Diné Bizaad, Dinékʼehǰí',
            'iso639-1' => 'nv',
            'iso639-2/t' => 'nav',
            'iso639-2/b' => 'nav',
            'iso639-3' => 'nav',
        ],
        'nde' => [
            'name' => 'Northern Ndebele',
            'native' => 'Isindebele',
            'iso639-1' => 'nd',
            'iso639-2/t' => 'nde',
            'iso639-2/b' => 'nde',
            'iso639-3' => 'nde',
        ],
        'nep' => [
            'name' => 'Nepali',
            'native' => 'नेपाली',
            'iso639-1' => 'ne',
            'iso639-2/t' => 'nep',
            'iso639-2/b' => 'nep',
            'iso639-3' => 'nep',
        ],
        'ndo' => [
            'name' => 'Ndonga',
            'native' => 'Owambo',
            'iso639-1' => 'ng',
            'iso639-2/t' => 'ndo',
            'iso639-2/b' => 'ndo',
            'iso639-3' => 'ndo',
        ],
        'nob' => [
            'name' => 'Norwegian Bokmål',
            'native' => 'Norsk Bokmål',
            'iso639-1' => 'nb',
            'iso639-2/t' => 'nob',
            'iso639-2/b' => 'nob',
            'iso639-3' => 'nob',
        ],
        'nno' => [
            'name' => 'Norwegian Nynorsk',
            'native' => 'Norsk Nynorsk',
            'iso639-1' => 'nn',
            'iso639-2/t' => 'nno',
            'iso639-2/b' => 'nno',
            'iso639-3' => 'nno',
        ],
        'nor' => [
            'name' => 'Norwegian',
            'native' => 'Norsk',
            'iso639-1' => 'no',
            'iso639-2/t' => 'nor',
            'iso639-2/b' => 'nor',
            'iso639-3' => 'nor + 2',
        ],
        'iii' => [
            'name' => 'Nuosu',
            'native' => 'ꆈꌠ꒿ Nuosuhxop',
            'iso639-1' => 'ii',
            'iso639-2/t' => 'iii',
            'iso639-2/b' => 'iii',
            'iso639-3' => 'iii',
        ],
        'nbl' => [
            'name' => 'Southern Ndebele',
            'native' => 'Isindebele',
            'iso639-1' => 'nr',
            'iso639-2/t' => 'nbl',
            'iso639-2/b' => 'nbl',
            'iso639-3' => 'nbl',
        ],
        'oci' => [
            'name' => 'Occitan',
            'native' => "Occitan, Lenga D'òc",
            'iso639-1' => 'oc',
            'iso639-2/t' => 'oci',
            'iso639-2/b' => 'oci',
            'iso639-3' => 'oci',
        ],
        'oji' => [
            'name' => 'Ojibwe, Ojibwa',
            'native' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
            'iso639-1' => 'oj',
            'iso639-2/t' => 'oji',
            'iso639-2/b' => 'oji',
            'iso639-3' => 'oji + 7',
        ],
        'chu' => [
            'name' => 'Old Church Slavonic, Church Slavonic, Old Bulgarian',
            'native' => 'ѩзыкъ словѣньскъ',
            'iso639-1' => 'cu',
            'iso639-2/t' => 'chu',
            'iso639-2/b' => 'chu',
            'iso639-3' => 'chu',
        ],
        'orm' => [
            'name' => 'Oromo',
            'native' => 'Afaan Oromoo',
            'iso639-1' => 'om',
            'iso639-2/t' => 'orm',
            'iso639-2/b' => 'orm',
            'iso639-3' => 'orm + 4',
        ],
        'ori' => [
            'name' => 'Oriya',
            'native' => 'ଓଡ଼ିଆ',
            'iso639-1' => 'or',
            'iso639-2/t' => 'ori',
            'iso639-2/b' => 'ori',
            'iso639-3' => 'ori',
        ],
        'oss' => [
            'name' => 'Ossetian, Ossetic',
            'native' => 'ирон æвзаг',
            'iso639-1' => 'os',
            'iso639-2/t' => 'oss',
            'iso639-2/b' => 'oss',
            'iso639-3' => 'oss',
        ],
        'pan' => [
            'name' => 'Panjabi, Punjabi',
            'native' => 'ਪੰਜਾਬੀ, پنجابی‎',
            'iso639-1' => 'pa',
            'iso639-2/t' => 'pan',
            'iso639-2/b' => 'pan',
            'iso639-3' => 'pan',
        ],
        'pli' => [
            'name' => 'Pāli',
            'native' => 'पाऴि',
            'iso639-1' => 'pi',
            'iso639-2/t' => 'pli',
            'iso639-2/b' => 'pli',
            'iso639-3' => 'pli',
        ],
        'fas' => [
            'name' => 'Persian (farsi)',
            'native' => 'فارسی',
            'iso639-1' => 'fa',
            'iso639-2/t' => 'fas',
            'iso639-2/b' => 'per',
            'iso639-3' => 'fas + 2',
        ],
        'pol' => [
            'name' => 'Polish',
            'native' => 'Język Polski, Polszczyzna',
            'iso639-1' => 'pl',
            'iso639-2/t' => 'pol',
            'iso639-2/b' => 'pol',
            'iso639-3' => 'pol',
        ],
        'pus' => [
            'name' => 'Pashto, Pushto',
            'native' => 'پښتو',
            'iso639-1' => 'ps',
            'iso639-2/t' => 'pus',
            'iso639-2/b' => 'pus',
            'iso639-3' => 'pus + 3',
        ],
        'por' => [
            'name' => 'Portuguese',
            'native' => 'Português',
            'iso639-1' => 'pt',
            'iso639-2/t' => 'por',
            'iso639-2/b' => 'por',
            'iso639-3' => 'por',
        ],
        'que' => [
            'name' => 'Quechua',
            'native' => 'Runa Simi, Kichwa',
            'iso639-1' => 'qu',
            'iso639-2/t' => 'que',
            'iso639-2/b' => 'que',
            'iso639-3' => 'que + 44',
        ],
        'roh' => [
            'name' => 'Romansh',
            'native' => 'Rumantsch Grischun',
            'iso639-1' => 'rm',
            'iso639-2/t' => 'roh',
            'iso639-2/b' => 'roh',
            'iso639-3' => 'roh',
        ],
        'run' => [
            'name' => 'Kirundi',
            'native' => 'Ikirundi',
            'iso639-1' => 'rn',
            'iso639-2/t' => 'run',
            'iso639-2/b' => 'run',
            'iso639-3' => 'run',
        ],
        'ron' => [
            'name' => 'Romanian',
            'native' => 'Limba Română',
            'iso639-1' => 'ro',
            'iso639-2/t' => 'ron',
            'iso639-2/b' => 'rum',
            'iso639-3' => 'ron',
        ],
        'rus' => [
            'name' => 'Russian',
            'native' => 'русский язык',
            'iso639-1' => 'ru',
            'iso639-2/t' => 'rus',
            'iso639-2/b' => 'rus',
            'iso639-3' => 'rus',
        ],
        'san' => [
            'name' => 'Sanskrit (saṁskṛta)',
            'native' => 'संस्कृतम्',
            'iso639-1' => 'sa',
            'iso639-2/t' => 'san',
            'iso639-2/b' => 'san',
            'iso639-3' => 'san',
        ],
        'srd' => [
            'name' => 'Sardinian',
            'native' => 'Sardu',
            'iso639-1' => 'sc',
            'iso639-2/t' => 'srd',
            'iso639-2/b' => 'srd',
            'iso639-3' => 'srd + 4',
        ],
        'snd' => [
            'name' => 'Sindhi',
            'native' => 'सिन्धी, سنڌي، سندھی‎',
            'iso639-1' => 'sd',
            'iso639-2/t' => 'snd',
            'iso639-2/b' => 'snd',
            'iso639-3' => 'snd',
        ],
        'sme' => [
            'name' => 'Northern Sami',
            'native' => 'Davvisámegiella',
            'iso639-1' => 'se',
            'iso639-2/t' => 'sme',
            'iso639-2/b' => 'sme',
            'iso639-3' => 'sme',
        ],
        'smo' => [
            'name' => 'Samoan',
            'native' => "Gagana Fa'a Samoa",
            'iso639-1' => 'sm',
            'iso639-2/t' => 'smo',
            'iso639-2/b' => 'smo',
            'iso639-3' => 'smo',
        ],
        'sag' => [
            'name' => 'Sango',
            'native' => 'Yângâ Tî Sängö',
            'iso639-1' => 'sg',
            'iso639-2/t' => 'sag',
            'iso639-2/b' => 'sag',
            'iso639-3' => 'sag',
        ],
        'srp' => [
            'name' => 'Serbian',
            'native' => 'српски језик',
            'iso639-1' => 'sr',
            'iso639-2/t' => 'srp',
            'iso639-2/b' => 'srp',
            'iso639-3' => 'srp',
        ],
        'gla' => [
            'name' => 'Scottish Gaelic, Gaelic',
            'native' => 'Gàidhlig',
            'iso639-1' => 'gd',
            'iso639-2/t' => 'gla',
            'iso639-2/b' => 'gla',
            'iso639-3' => 'gla',
        ],
        'sna' => [
            'name' => 'Shona',
            'native' => 'Chishona',
            'iso639-1' => 'sn',
            'iso639-2/t' => 'sna',
            'iso639-2/b' => 'sna',
            'iso639-3' => 'sna',
        ],
        'sin' => [
            'name' => 'Sinhala, Sinhalese',
            'native' => 'සිංහල',
            'iso639-1' => 'si',
            'iso639-2/t' => 'sin',
            'iso639-2/b' => 'sin',
            'iso639-3' => 'sin',
        ],
        'slk' => [
            'name' => 'Slovak',
            'native' => 'Slovenčina, Slovenský Jazyk',
            'iso639-1' => 'sk',
            'iso639-2/t' => 'slk',
            'iso639-2/b' => 'slo',
            'iso639-3' => 'slk',
        ],
        'slv' => [
            'name' => 'Slovene',
            'native' => 'Slovenski Jezik, Slovenščina',
            'iso639-1' => 'sl',
            'iso639-2/t' => 'slv',
            'iso639-2/b' => 'slv',
            'iso639-3' => 'slv',
        ],
        'som' => [
            'name' => 'Somali',
            'native' => 'Soomaaliga, Af Soomaali',
            'iso639-1' => 'so',
            'iso639-2/t' => 'som',
            'iso639-2/b' => 'som',
            'iso639-3' => 'som',
        ],
        'sot' => [
            'name' => 'Southern Sotho',
            'native' => 'Sesotho',
            'iso639-1' => 'st',
            'iso639-2/t' => 'sot',
            'iso639-2/b' => 'sot',
            'iso639-3' => 'sot',
        ],
        'spa' => [
            'name' => 'Spanish, Castilian',
            'native' => 'Español, Castellano',
            'iso639-1' => 'es',
            'iso639-2/t' => 'spa',
            'iso639-2/b' => 'spa',
            'iso639-3' => 'spa',
        ],
        'sun' => [
            'name' => 'Sundanese',
            'native' => 'Basa Sunda',
            'iso639-1' => 'su',
            'iso639-2/t' => 'sun',
            'iso639-2/b' => 'sun',
            'iso639-3' => 'sun',
        ],
        'swa' => [
            'name' => 'Swahili',
            'native' => 'Kiswahili',
            'iso639-1' => 'sw',
            'iso639-2/t' => 'swa',
            'iso639-2/b' => 'swa',
            'iso639-3' => 'swa + 2',
        ],
        'ssw' => [
            'name' => 'Swati',
            'native' => 'Siswati',
            'iso639-1' => 'ss',
            'iso639-2/t' => 'ssw',
            'iso639-2/b' => 'ssw',
            'iso639-3' => 'ssw',
        ],
        'swe' => [
            'name' => 'Swedish',
            'native' => 'Svenska',
            'iso639-1' => 'sv',
            'iso639-2/t' => 'swe',
            'iso639-2/b' => 'swe',
            'iso639-3' => 'swe',
        ],
        'tam' => [
            'name' => 'Tamil',
            'native' => 'தமிழ்',
            'iso639-1' => 'ta',
            'iso639-2/t' => 'tam',
            'iso639-2/b' => 'tam',
            'iso639-3' => 'tam',
        ],
        'tel' => [
            'name' => 'Telugu',
            'native' => 'తెలుగు',
            'iso639-1' => 'te',
            'iso639-2/t' => 'tel',
            'iso639-2/b' => 'tel',
            'iso639-3' => 'tel',
        ],
        'tgk' => [
            'name' => 'Tajik',
            'native' => 'тоҷикӣ, Toğikī, تاجیکی‎',
            'iso639-1' => 'tg',
            'iso639-2/t' => 'tgk',
            'iso639-2/b' => 'tgk',
            'iso639-3' => 'tgk',
        ],
        'tha' => [
            'name' => 'Thai',
            'native' => 'ไทย',
            'iso639-1' => 'th',
            'iso639-2/t' => 'tha',
            'iso639-2/b' => 'tha',
            'iso639-3' => 'tha',
        ],
        'tir' => [
            'name' => 'Tigrinya',
            'native' => 'ትግርኛ',
            'iso639-1' => 'ti',
            'iso639-2/t' => 'tir',
            'iso639-2/b' => 'tir',
            'iso639-3' => 'tir',
        ],
        'bod' => [
            'name' => 'Tibetan Standard, Tibetan, Central',
            'native' => 'བོད་ཡིག',
            'iso639-1' => 'bo',
            'iso639-2/t' => 'bod',
            'iso639-2/b' => 'tib',
            'iso639-3' => 'bod',
        ],
        'tuk' => [
            'name' => 'Turkmen',
            'native' => 'Türkmen, түркмен',
            'iso639-1' => 'tk',
            'iso639-2/t' => 'tuk',
            'iso639-2/b' => 'tuk',
            'iso639-3' => 'tuk',
        ],
        'tgl' => [
            'name' => 'Tagalog',
            'native' => 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔',
            'iso639-1' => 'tl',
            'iso639-2/t' => 'tgl',
            'iso639-2/b' => 'tgl',
            'iso639-3' => 'tgl',
        ],
        'tsn' => [
            'name' => 'Tswana',
            'native' => 'Setswana',
            'iso639-1' => 'tn',
            'iso639-2/t' => 'tsn',
            'iso639-2/b' => 'tsn',
            'iso639-3' => 'tsn',
        ],
        'ton' => [
            'name' => 'Tonga',
            'native' => 'Faka Tonga',
            'iso639-1' => 'to',
            'iso639-2/t' => 'ton',
            'iso639-2/b' => 'ton',
            'iso639-3' => 'ton',
        ],
        'tur' => [
            'name' => 'Turkish',
            'native' => 'Türkçe',
            'iso639-1' => 'tr',
            'iso639-2/t' => 'tur',
            'iso639-2/b' => 'tur',
            'iso639-3' => 'tur',
        ],
        'tso' => [
            'name' => 'Tsonga',
            'native' => 'Xitsonga',
            'iso639-1' => 'ts',
            'iso639-2/t' => 'tso',
            'iso639-2/b' => 'tso',
            'iso639-3' => 'tso',
        ],
        'tat' => [
            'name' => 'Tatar',
            'native' => 'татар теле, Tatar Tele',
            'iso639-1' => 'tt',
            'iso639-2/t' => 'tat',
            'iso639-2/b' => 'tat',
            'iso639-3' => 'tat',
        ],
        'twi' => [
            'name' => 'Twi',
            'native' => 'Twi',
            'iso639-1' => 'tw',
            'iso639-2/t' => 'twi',
            'iso639-2/b' => 'twi',
            'iso639-3' => 'twi',
        ],
        'tah' => [
            'name' => 'Tahitian',
            'native' => 'Reo Tahiti',
            'iso639-1' => 'ty',
            'iso639-2/t' => 'tah',
            'iso639-2/b' => 'tah',
            'iso639-3' => 'tah',
        ],
        'uig' => [
            'name' => 'Uyghur, Uighur',
            'native' => 'Uyƣurqə, ئۇيغۇرچە‎',
            'iso639-1' => 'ug',
            'iso639-2/t' => 'uig',
            'iso639-2/b' => 'uig',
            'iso639-3' => 'uig',
        ],
        'ukr' => [
            'name' => 'Ukrainian',
            'native' => 'українська мова',
            'iso639-1' => 'uk',
            'iso639-2/t' => 'ukr',
            'iso639-2/b' => 'ukr',
            'iso639-3' => 'ukr',
        ],
        'urd' => [
            'name' => 'Urdu',
            'native' => 'اردو',
            'iso639-1' => 'ur',
            'iso639-2/t' => 'urd',
            'iso639-2/b' => 'urd',
            'iso639-3' => 'urd',
        ],
        'uzb' => [
            'name' => 'Uzbek',
            'native' => 'O‘zbek, ўзбек, أۇزبېك‎',
            'iso639-1' => 'uz',
            'iso639-2/t' => 'uzb',
            'iso639-2/b' => 'uzb',
            'iso639-3' => 'uzb + 2',
        ],
        'ven' => [
            'name' => 'Venda',
            'native' => 'Tshivenḓa',
            'iso639-1' => 've',
            'iso639-2/t' => 'ven',
            'iso639-2/b' => 'ven',
            'iso639-3' => 'ven',
        ],
        'vie' => [
            'name' => 'Vietnamese',
            'native' => 'Tiếng Việt',
            'iso639-1' => 'vi',
            'iso639-2/t' => 'vie',
            'iso639-2/b' => 'vie',
            'iso639-3' => 'vie',
        ],
        'vol' => [
            'name' => 'Volapük',
            'native' => 'Volapük',
            'iso639-1' => 'vo',
            'iso639-2/t' => 'vol',
            'iso639-2/b' => 'vol',
            'iso639-3' => 'vol',
        ],
        'wln' => [
            'name' => 'Walloon',
            'native' => 'Walon',
            'iso639-1' => 'wa',
            'iso639-2/t' => 'wln',
            'iso639-2/b' => 'wln',
            'iso639-3' => 'wln',
        ],
        'cym' => [
            'name' => 'Welsh',
            'native' => 'Cymraeg',
            'iso639-1' => 'cy',
            'iso639-2/t' => 'cym',
            'iso639-2/b' => 'wel',
            'iso639-3' => 'cym',
        ],
        'wol' => [
            'name' => 'Wolof',
            'native' => 'Wollof',
            'iso639-1' => 'wo',
            'iso639-2/t' => 'wol',
            'iso639-2/b' => 'wol',
            'iso639-3' => 'wol',
        ],
        'fry' => [
            'name' => 'Western Frisian',
            'native' => 'Frysk',
            'iso639-1' => 'fy',
            'iso639-2/t' => 'fry',
            'iso639-2/b' => 'fry',
            'iso639-3' => 'fry',
        ],
        'xho' => [
            'name' => 'Xhosa',
            'native' => 'Isixhosa',
            'iso639-1' => 'xh',
            'iso639-2/t' => 'xho',
            'iso639-2/b' => 'xho',
            'iso639-3' => 'xho',
        ],
        'yid' => [
            'name' => 'Yiddish',
            'native' => 'ייִדיש',
            'iso639-1' => 'yi',
            'iso639-2/t' => 'yid',
            'iso639-2/b' => 'yid',
            'iso639-3' => 'yid + 2',
        ],
        'yor' => [
            'name' => 'Yoruba',
            'native' => 'Yorùbá',
            'iso639-1' => 'yo',
            'iso639-2/t' => 'yor',
            'iso639-2/b' => 'yor',
            'iso639-3' => 'yor',
        ],
        'zha' => [
            'name' => 'Zhuang, Chuang',
            'native' => 'Saɯ Cueŋƅ, Saw Cuengh',
            'iso639-1' => 'za',
            'iso639-2/t' => 'zha',
            'iso639-2/b' => 'zha',
            'iso639-3' => 'zha + 16',
        ],
        'zul' => [
            'name' => 'Zulu',
            'native' => 'Isizulu',
            'iso639-1' => 'zu',
            'iso639-2/t' => 'zul',
            'iso639-2/b' => 'zul',
            'iso639-3' => 'zul',
        ],
    ];

    /**
     * Get all the available language names.
     *
     * @codeCoverageIgnore
     *
     * @return array<int, string>
     */
    public static function names(): array
    {
        return collect(self::all())
            ->map(fn ($item) => $item['name'])
            ->values()
            ->toArray();
    }

    /**
     * Get all the available languages for the selector.
     *
     * @return array<string, string>
     */
    public static function forSelector(): array
    {
        return collect(self::all())
            ->map(fn ($item) => $item['name'])
            ->toArray();
    }

    /**
     * Get all the available languages keyed by the 3-letter ISO code.
     *
     * @return array<string, array<string, string>>
     */
    public static function all(): array
    {
        return self::LANGUAGES;
    }
}
