<?php

namespace Tests\Feature\Arachno;

use App\Models\Arachno\Source;
use App\Models\Geonames\Location;
use Illuminate\Database\Eloquent\Factories\Factory;
use Tests\Feature\Abstracts\CrudTestCase;

class SourceTest extends CrudTestCase
{
    /** @var string */
    protected string $sortBy = 'title';

    protected bool $collaborate = true;

    /**
     * Get the class to be used for the CRUD operations.
     *
     * @return string
     */
    protected static function resource(): string
    {
        return Source::class;
    }

    /**
     * Get base resource route which will be added the suffix actions.
     *
     * @return string
     */
    protected static function resourceRoute(): string
    {
        return 'collaborate.sources';
    }

    /**
     * The list of database columns that should be visible on the pages.
     *
     * @return string[]
     */
    protected static function visibleFields(): array
    {
        return ['title'];
    }

    /**
     * The list of database columns that should be visible on the pages with forms.
     *
     * @return string[]
     */
    protected static function visibleLabels(): array
    {
        return ['Title', 'Source URL', 'Source Content'];
    }

    /**
     * {@inheritDoc}
     */
    protected static function preCreate(Factory $factory, string $route): Factory
    {
        $location = Location::factory()->create();

        if ($route === 'store') {
            return parent::preCreate($factory, $route)->state(fn () => ['locations' => [$location->id]]);
        }

        return parent::preCreate($factory, $route); // TODO: Change the autogenerated stub
    }
}
